History reinforced
GrafVonTee/triangle_intersections pull request #102
Opened 2023-06-06 10:35 UTC by GrafVonTee

2023-06-06 10:54 UTC, Kitsumetri requested changes

2023-06-06 10:54 UTC, Kitsumetri commented on include/StatesLibrary.h
> +        size_t getSize() const { return m_states.size(); }
Эти методы стоит внести в .cpp файл

2023-06-06 10:54 UTC, Kitsumetri commented on src/drawing/DrawImage.cpp
> +        auto figures = library.getStateCopy();
Неясно что за тип возвращается, напиши лучше типизацию вместо auto

2023-06-06 10:54 UTC, Kitsumetri commented on src/drawing/DrawImage.cpp
> +        // ??? copy-paste?
???

2023-06-06 10:54 UTC, Kitsumetri commented on src/drawing/DrawImage.cpp
>          }
Лишние скобки, и так понятно, что в for только условие

2023-06-06 10:54 UTC, Kitsumetri commented on src/utils/StatesLibrary.cpp
>          auto &manipulator = StatesLibrary::getInstance();
Не понятно какой тип данных возвращается, лучше использовать обычную типизацию

2023-06-06 10:54 UTC, Kitsumetri commented on src/utils/StatesLibrary.cpp
>          auto &state = manipulator.getStateRef();
Тоже неясно какой тип данных &state. Лучше убрать auto

2023-06-06 10:54 UTC, Kitsumetri commented on src/utils/StatesLibrary.cpp
> +        auto figures = manipulator.getStateCopy();
Ещё 2 раза auto. Не читав код в StatesLibrary, неясно какой тип данных возвращают методы

2023-06-06 11:10 UTC, Kitsumetri commented on src/drawing/DrawImage.cpp
>          ImGui::Text("%s", title.c_str());
А к чему этот код с условием?

2023-06-06 11:49 UTC, Kitsumetri approved these changes

2023-06-11 07:37 UTC, DanTimson approved these changes

2023-06-11 07:38 UTC, merged